### ISSUE TITLE
Incorrect case for Fizzbuzz, fizz and buzz.

### ISSUE THREAD

**Issue by barberboy** [sdtorres2/webtech#4]
The logic for FizzBuzz is great, but the case does not match the assignment description.

You should be logging "[FizzBuzz](https://github.com/sdtorres2/webtech/blob/master/fibuzz.js#L7)", "[Fizz](https://github.com/sdtorres2/webtech/blob/master/fibuzz.js#L11)", and "[Buzz](https://github.com/sdtorres2/webtech/blob/master/fibuzz.js#L15)".

**Comment by sdtorres2** [comment]
Changed cases
